#!/bin/bash

make -C ../ -j src.build

export LD_LIBRARY_PATH=/usr/local/cuda/lib64:/engshare/libs/ncclx/nccl-2.27.7/build/lib/

export NCCL_FIRST_COMM_AS_WORLD=1
export NCCL_IB_ADAPTIVE_ROUTING=1
export NCCL_IB_QPS_PER_CONNECTION=16
export NCCL_IB_SPLIT_DATA_ON_QPS=0
export NCCL_BUFFSIZES_CONFIG_ENABLE=1
export NCCL_COLLTRACE_SLOW_COLL_THRESHOLD_BY_PG=ANY:4000
export NCCL_COLLTRACE=trace
export NCCL_PROXYTRACE=trace
export NCCL_ERROR_TRACE_ENABLE=1
export NCCL_SCUBA_STACK_TRACE_ON_ERROR_ENABLED=1
export NCCL_COMM_ABORT_SCOPE=none
export NCCL_COMM_DUMP_ENABLE_PROCESS_GLOBAL_ERRORS=1
export NCCL_IB_ENABLE_REPORT_TO_PROCESS_GLOBAL_ERRORS=1
export NCCL_PROCESS_GLOBAL_ERRORS_MAX_STACK_TRACES=20
export NCCL_COMM_EVENT_LOGGING=scuba:nccl_structured_logging
export NCCL_ERROR_EVENT_LOGGING=scuba:nccl_error_logging
export NCCL_PXN_DISABLE=1
export NCCL_MEM_USE_SLAB_ALLOCATOR=1
export NCCL_MEMORY_EVENT_LOGGING=scuba:nccl_memory_logging
export NCCL_SCUBA_LOG_FILE_PREFIX=/tmp
export NCCL_SLOW_RANK_ENABLE=1
export NCCL_SLOW_RANK_LOGGING=scuba:nccl_profiler_slow_rank
export NCCL_DEBUG=INFO
export NCCL_DEBUG_SUBSYS=INIT,ENV
export NCCL_IB_TIMEOUT=20
export NCCL_MIN_NCHANNELS=4
export NCCL_NET_OVERHEAD=2750
export NCCL_SET_THREAD_NAME=1


../build/examples/HelloWorld

