/*************************************************************************
 * Copyright (c) 2023, NVIDIA CORPORATION. All rights reserved.
 * Copyright (c) 2023, Meta Platforms, Inc. and affiliates.
 *
 * See LICENSE.txt for license information
 ************************************************************************/

#ifndef TUNER_V7_H_
#define TUNER_V7_H_

#include "tuner_v6.h"

// V6 constants and NVL domain info are the same as V5 - no minChunkSize table needed
// Chunk size overrides are handled via the getChunkSize callback instead
typedef ncclNvlDomainInfo_v5_t ncclNvlDomainInfo_v7_t;

#define NCCL_NUM_COMPCAPS_V7 5

typedef struct {
  double baseLatencies[NCCL_NUM_ALGORITHMS_V5][NCCL_NUM_PROTOCOLS_V5];
  double hwLatencies[NCCL_NUM_HW_LINKS_V5][NCCL_NUM_ALGORITHMS_V5][NCCL_NUM_PROTOCOLS_V5];

  double llMaxBws[NCCL_NUM_COMPCAPS_V7][NCCL_NUM_TUNING_SCALES_V5];
  double perChMaxRingLL128Bws[NCCL_NUM_COMPCAPS_V7][NCCL_NUM_TUNING_SCALES_V5];
  double perChMaxTreeLL128Bws[NCCL_NUM_COMPCAPS_V7][NCCL_NUM_TUNING_SCALES_V5];
  double perChMaxTreeBws[NCCL_NUM_COMPCAPS_V7][NCCL_NUM_TUNING_SCALES_V5];
  double perChMaxNVLSTreeBws[NCCL_NUM_COMPCAPS_V7][NCCL_NUM_TUNING_SCALES_V5];

} ncclTunerConstants_v7_t;

// Convenient constant conversion functions.
inline void ncclTunerConstants_v7_to_v5(ncclTunerConstants_v5_t* dst, const ncclTunerConstants_v7_t* src) {
  memcpy(dst->baseLatencies, src->baseLatencies, sizeof(dst->baseLatencies));
  memcpy(dst->hwLatencies, src->hwLatencies, sizeof(dst->hwLatencies));

  memcpy(dst->llMaxBws, src->llMaxBws, sizeof(dst->llMaxBws));
  memcpy(dst->perChMaxRingLL128Bws, src->perChMaxRingLL128Bws, sizeof(dst->perChMaxRingLL128Bws));
  memcpy(dst->perChMaxTreeLL128Bws, src->perChMaxTreeLL128Bws, sizeof(dst->perChMaxTreeLL128Bws));
  memcpy(dst->perChMaxTreeBws, src->perChMaxTreeBws, sizeof(dst->perChMaxTreeBws));
  memcpy(dst->perChMaxNVLSTreeBws, src->perChMaxNVLSTreeBws, sizeof(dst->perChMaxNVLSTreeBws));
}

inline void ncclTunerConstants_v5_to_v7(ncclTunerConstants_v7_t* dst, const ncclTunerConstants_v5_t* src) {
  memcpy(dst->baseLatencies, src->baseLatencies, sizeof(src->baseLatencies));
  memcpy(dst->hwLatencies, src->hwLatencies, sizeof(src->hwLatencies));

  memcpy(dst->llMaxBws, src->llMaxBws, sizeof(src->llMaxBws));
  memcpy(dst->perChMaxRingLL128Bws, src->perChMaxRingLL128Bws, sizeof(src->perChMaxRingLL128Bws));
  memcpy(dst->perChMaxTreeLL128Bws, src->perChMaxTreeLL128Bws, sizeof(src->perChMaxTreeLL128Bws));
  memcpy(dst->perChMaxTreeBws, src->perChMaxTreeBws, sizeof(src->perChMaxTreeBws));
  memcpy(dst->perChMaxNVLSTreeBws, src->perChMaxNVLSTreeBws, sizeof(src->perChMaxNVLSTreeBws));
}

// API to be implemented by external tuner
typedef struct {
  // Name of the tuner
  const char* name;

  // Initializes tuner states.
  // Inputs:
  //   - commId: communicator identifier
  //   - nRanks: number of ranks in current communicator. Each communicator initialize its own tuner.
  //   - nNodes: number of nodes in current communicator.
  //   - logFunction: a logFunction can be useful to integrate logging together with NCCL core.
  //   - nvlDomainInfo: NVL domain information struct
  // Outputs:
  //   - context: tuner context object
  // Input/Output:
  //   - constants: tuner constants
  ncclResult_t (*init)(void** ctx, uint64_t commId, size_t nRanks, size_t nNodes, ncclDebugLogger_t logFunction,
                       ncclNvlDomainInfo_v7_t* nvlDomainInfo, ncclTunerConstants_v7_t* constants);

  // Gets info (algo, protocol, number of ctas and threads) for a given collective.
  // Inputs:
  //   - context: tuner context object
  //   - collType: collective type , e.g., allreduce, allgather…
  //   - nBytes: collective size in bytes
  //   - numPipeOps: number of operations in the group
  //   - numAlgo: number of algorithms in collCostTable
  //   - numProto: number of protocols in collCostTable
  //   - regBuff: can register user buffer
  //
  // Outputs:
  //   - nChannels: number of channels (hence SMs) to be used.
  //
  // InOut:
  //   - collCostTable: collective cost table, generated by NCCL core, containing algo|proto|time entries for collType.
  //                    NCCL core sets ignored algo/proto cost table entries to -1.0 (NCCL_ALGO_PROTO_IGNORE).
  //
  // If getCollInfo() does not return ncclSuccess, NCCL will fall back to the
  // default tuning for the given collective.
  // Also, the plugin is allowed to not set any output, or set only the
  // algorithm and protocol, but not only the algorithm or only the protocol.
  // Unset fields will be set automatically by NCCL.
  ncclResult_t (*getCollInfo)(void* context, ncclFunc_t collType, size_t nBytes, int numPipeOps, float** collCostTable,
                              int numAlgo, int numProto, int regBuff, int* nChannels);

  // Terminates the plugin and cleans up any resources that the plugin allocated.
  // context: tuner context object
  ncclResult_t (*finalize)(void* context);

  // Allows the tuner plugin to override the chunk size computed by NCCL.
  // This function is optional - if NULL, NCCL's computed chunk size is used.
  // Inputs:
  //   - context: tuner context object
  //   - collType: collective type, e.g., allreduce, allgather...
  //   - nBytes: collective size in bytes
  //   - algo: selected algorithm (NCCL_ALGO_*)
  //   - proto: selected protocol (NCCL_PROTO_*)
  //   - nChannels: number of channels being used
  // InOut:
  //   - chunkSize: pointer to the chunk size computed by NCCL. The plugin can
  //                read and modify this value. NCCL will clamp the result to
  //                the maximum allowed chunk size based on buffer constraints.
  ncclResult_t (*getChunkSize)(void* context, ncclFunc_t collType, size_t nBytes, int algo, int proto, int nChannels,
                               size_t* chunkSize);
} ncclTuner_v7_t;

#endif
