name: Formatting

on:
  pull_request:
    branches:
      - '*'

jobs:
  ci-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Check Formatting
        run: |
          maint/formatter.bash > /dev/null
          echo "Unformatted files: $(git diff HEAD --name-only)"
          git diff HEAD --exit-code > /dev/null

